export class CreatePermitRequestBody {
  activity_type: string;
  actual_end_date: string;
  actual_start_date: string;
  alteration_reason: string;
  alteration_status: string;
  application_id: number;
  area_name: string;
  assessment_comments: string;
  assessment_discount: number;
  assessment_status: string;
  close_footway: string;
  collaboration_details: string;
  collaboration_type: string;
  collaborative_working_flag: boolean;
  collaborative_works: string;
  conditions: {
    comment: string;
    condition: string
  }[];
  cost_risk: number;
  customer_risk: number;
  department_id: number;
  department_name: string;
  draft_alteration_id: number;
  draft_application_id: number;
  draft_work_type: string;
  early_start_pre_approval_flag: boolean;
  early_start_reason: string;
  environmental_flag: boolean;
  excavation_flag: boolean;
  geometry: {
    coordinates: number[];
    type: string
  };
  highway_authority_id: number;
  highway_authority_name: string;
  is_an_old_permit: boolean;
  lane_rental_flag: boolean;
  location_description: string;
  location_types: string;
  org_id: number;
  pending_change_details: string;
  permit_reference_number: string;
  pre_approval_authoriser: string;
  pre_approval_details: string;
  project_reference_number: string;
  promoter_organisation: string;
  promoter_prefix: string;
  proposed_end_date: string;
  proposed_start_date: string;
  reasonable_period_end_date: string;
  reasons_for_refusal: string;
  revoke_reason: string;
  road_category: number;
  secondary_contact: string;
  secondary_contact_email: string;
  secondary_contact_number: string;
  special_designations: {
    special_desig_description: string;
    special_desig_end_time: number;
    special_desig_location_text: string;
    special_desig_periodicity_code: number;
    special_desig_start_time: number;
    street_special_desig_code: number
  }[];
  status: string;
  status_value: string;
  street_name: string;
  town: string;
  traffic_management_risk: number;
  traffic_management_type: string;
  traffic_sensitive_flag: boolean;
  ttro_required_flag: boolean;
  usrn: number;
  work_category: string;
  work_description: string;
  work_id: number;
  work_reference_number: string;
  work_status: string;
  work_status_value: string;
  work_type: string
  constructor() { }
}
